# Hawk Multi-Camera Rig Configuration

stereo_cameras:
  - name: 'front'
    left_topic: '/front/left/image_rect'
    right_topic: '/front/right/image_rect'
    left_camera:
      transform:            # identity – this camera defines the rig origin
        - [1, 0, 0, -0.075]
        - [0, 1, 0, 0.0]
        - [0, 0, 1, 0.0]
    right_camera:
      transform:
        - [1, 0, 0, 0.075]
        - [0, 1, 0, 0.0]
        - [0, 0, 1, 0.0]

# 28.2 (outer faces distance) - 2 * 1.6 (outer face to origin) = 25cm
  - name: 'back'
    left_topic: '/back/left/image_rect'
    right_topic: '/back/right/image_rect'
    left_camera:
      transform:            # 180° around Y
        - [-1, 0, 0,  0.075]
        - [ 0, 1, 0,  0.0]
        - [ 0, 0, -1, 0.25]
    right_camera:
      transform:
        - [-1, 0, 0, -0.075]
        - [ 0, 1, 0,  0.0]
        - [ 0, 0, -1, 0.25]
